name: Update BloraCloud Stats

on:
  push:
    paths:
      - 'indexes/**'
      - 'README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install requests
        run: pip install requests

      - name: Update README
        run: python update_readme.py

      - name: Commit changes
        run: |
          git config --local user.name "BloraCloud Bot"
          git config --local user.email "bot@bloracloud.com"
          git add README.md
          git commit -m "Update BloraCloud stats" || echo "No changes to commit"
          git push
